name = "whatsapp-api"
main = "worker.js"
compatibility_date = "2026-07-23"

[[d1_databases]]
binding = "DB"
database_name = "whatsapp-db"
database_id = "fec67ff7-f37f-4ed9-a467-42cf87ef749c"

[assets]
directory = "../public"
binding = "ASSETS"


[triggers]
crons = ["30 10 * * *"] # Daily at 10:30 UTC / 4:00 PM IST

