name = "whatsapp-api"
main = "worker.js"
compatibility_date = "2026-07-23"

[[d1_databases]]
binding = "DB"
database_name = "whatsapp-db"
database_id = "938a7654-f89d-48c5-b3ee-0e8df809638a"

[assets]
directory = "../public"
binding = "ASSETS"
